apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  labels:
    helm.sh/chart: {{ .Chart.Name }}
data:
  config.yaml: |
    enableUserWorkload: true 