{{- if .Values.cruiseControl.deployRebalance }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: kafka-rebalance
  namespace: {{ include "kafka.namespace" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}
    app: strimzi
    strimzi.io/cluster: {{ .Values.global.kafka.clusterName }} . }}
    {{- include "kafka.labels" $ | nindent 4 }}
spec:
  goals:
    - CpuCapacityGoal
    - NetworkInboundCapacityGoal
    - DiskCapacityGoal
    - RackAwareGoal
    - MinTopicLeadersPerBrokerGoal
    - NetworkOutboundCapacityGoal
    - ReplicaCapacityGoal
{{- end }}
