apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: producer-high
  name: producer-high
spec:
  replicas: 3
  selector:
    matchLabels:
      app: producer-high
  template:
    metadata:
      labels:
        app: producer-high
    spec:
      containers:
      - name: producer-high
        image: strimzi/hello-world-producer:latest
        resources:
          limits:
            cpu: "200m"
            memory: 256Mi
          requests:
            cpu: "200m"
            memory: 256Mi
        env:
          - name: BOOTSTRAP_SERVERS
            value: {{ .Values.kafka.name }}-kafka-bootstrap.{{ include "producers.namespace" . }}.svc.cluster.local:9092
          - name: TOPIC
            value: "topic.high"
          - name: DELAY_MS
            value: "100"
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000000"
          - name: MESSAGES_PER_TRANSACTION
            value: "50"
          - name: PRODUCER_ACKS
            value: "0"