---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-serviceaccount
  namespace: {{ include "strimzi-monitoring.namespace" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}
    app: strimzi
    {{- include "strimzi-monitoring.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: grafana-serviceaccount
  name: grafana-serviceaccount-token
  namespace: {{ include "strimzi-monitoring.namespace" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}
    {{- include "strimzi-monitoring.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "grafana-%s-binding" (include "strimzi-monitoring.namespace" .) | trunc 63 | trimSuffix "-" }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}
    app: strimzi
    {{- include "strimzi-monitoring.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: grafana-serviceaccount
    namespace: {{ include "strimzi-monitoring.namespace" . }}
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
