apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: {{ include "strimzi-monitoring.namespace" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}
    app: strimzi
    {{- include "strimzi-monitoring.labels" . | nindent 4 }}
data:
  datasource.yaml: |
    apiVersion: 1

    datasources:
    - name: Prometheus
      type: prometheus
      url: {{ .Values.grafana.datasource.url }}
      access: proxy
      basicAuth: false
      withCredentials: false
      isDefault: true
      jsonData:
        timeInterval: 5s
        tlsSkipVerify: true
        httpHeaderName1: "Authorization"
      secureJsonData:
        httpHeaderValue1: "Bearer $SERVICE_ACCOUNT_TOKEN" 
      editable: true
