apiVersion: v1
kind: Secret
metadata:
  name: grafana-notifiers-config
  namespace: {{ include "strimzi-monitoring.namespace" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}
    app: strimzi
    {{- include "strimzi-monitoring.labels" . | nindent 4 }}
stringData:
  notifiers.yaml: |
    notifiers:
      - name: 'Slack'
        type: slack
        uid: slack1
        overridePriority: true
        is_default: true
        send_reminder: true
        frequency: 1h
        disable_resolve_message: false
        settings:
          recipient: {{ .Values.grafana.notifiers.slack.recipient | quote }}
          uploadImage: true
          autoClose: true
        secure_settings:
          token: ${GRAFANA_NOTIFIERS_SLACK_TOKEN} 
          url: ${GRAFANA_NOTIFIERS_SLACK_URL}
      - name: 'Teams'
        type: teams
        uid: msteams1
        is_default: false
        send_reminder: false
        frequency: 1h
        disable_resolve_message: false
        settings:
          url: ${GRAFANA_NOTIFIERS_TEAMS_URL}
    delete_notifiers:
    - name: 'Slack'
      uid: 'slack1'
    - name: 'Teams'
      uid: 'msteams1'